sonar.projectKey=Abira24_Task_Tracker_Application
sonar.organization=abira24
sonar.projectName=Task_Tracker_Application
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/*.test.*,**/*.spec.*
sonar.tests=.
sonar.test.inclusions=**/*.test.*,**/*.spec.*
sonar.sourceEncoding=UTF-8
